### ISSUE TITLE
Needs Instructions

### ISSUE THREAD

**Issue by LuRsT** [jlord/places#2]
I want to have my own but I'm having trouble knowing what data to put in the spreadsheet.

Also an easy way to change it without messing with the `index.html` would be awesome.

Good project idea :+1:

**Comment by jlord** [comment]
Hey @LuRsT! Glad you're into this! I've recently started it but haven't finished it yet so there's no readme right now. But :soon:  When there is a fleshed out readme, then it's ready! :)
